parallax_bg.parallax_element.*:
  type: config_entity
  label: 'Parallax element config'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    selector:
      type: label
      label: 'Selector'
    position:
      type: label
      label: 'Position'
    speed:
      type: label
      label: 'Speed'
